name: Željko Benović
github_name: zeljkobenovic
github_url: https://github.com/ZeljkoBenovic
linked_in_url: https://www.linkedin.com/in/zeljko-benovic
email: benoviczeljko87@gmail.com
roles:
    - Kubernetes
    - Helm
    - DevSecOps
    - GigaChad
projects:
    - name: Govein
      project_url: https://github.com/ZeljkoBenovic/govein
      description: Complete solution for your Veeam B&R observability.
    - name: Gombak
      project_url: https://github.com/ZeljkoBenovic/gombak
      description: Mikrotik router discovery and backup service.
    - name: TSBC
      project_url: https://github.com/ZeljkoBenovic/tsbc
      description: Teams SBC - connect your PBX with MS Teams.
    - name: Vmex
      project_url: https://github.com/ZeljkoBenovic/vmex
      description: Filter and export your VMWare VMs into an excel report.
    - name: Kmon
      project_url: https://github.com/ZeljkoBenovic/kmon
      description: Swiss army knife for K8s administrators using k9s TUI.
job_roles:
  - title: Senior Platform Engineer @ Linea
    description: |- 
      Maintaining EKS/GitHub/ArgoCD/Helm stack. 
      Building platform tools. 
      Building Kubernetes operators.
      Keeping Linea blockchain running.
  - title: Senior DevOps Engineer @ Route3
    description: Engineered a GitOps framework leveraging GitHub, GitHub Actions, AWS IAM, AWS OIDC and AWS SSM, all orchestrated seamlessly with Terraform.
  - title: Senior DevOps Engineer @ Polygon Labs
    description: Among the top 5 core contributors to the now deprecated Polygon project - Polygon Edge.
